### ISSUE TITLE
It seems that maps are not captured when exporting

### ISSUE THREAD

**Issue by Mallabarius** [MesseBasseProduction/MesseMap#8]
<img width="1145" alt="Skjermbilde 2023-02-14 kl  23 43 47" src="https://user-images.githubusercontent.com/122237959/218880041-995d1cfa-205e-4854-b612-7beeb86cbf3b.png">

Thanks for the wonderful project.
It seems that maps are not captured when exporting. Have tried several browsers such as FF, Safari, Chrome and Edge both with Mac and Win. Makes no difference, all are exported without map image.

**Comment by Mallabarius** [comment]
looks like some work but most don't. e.g. mono comes without a map when exporting

**Comment by ArthurBeaulieu** [comment]
Hello, sorry I had no time to check on that before. I'll have a look next week and let you know

**Comment by ArthurBeaulieu** [comment]
Closing the issue, for the record here are some information about this :
- The production runs on a github page as of today (and this will change in the coming weeks, because of the following points)
- Mapiful provider (which provides among others, Mono tile map) changed their cross-origin policy, that lead to this issue. Maps provided by Mapiful are marked with *(M)* suffix in map list.
- An express js, is now used as a proxy to avoid tainted canvas (which made map impossible to render) is now required

I'm scheduling to deploy a dedicated production environment with Messe basse production team, it may take several weeks before we provide a new production supporting this proxy. In the meantime, if you still want to use the app here is your temporary way : 

- Clone the repository and install dependencies : `$ git clone https://github.com/MesseBasseProduction/MesseMap && cd MesseMap && npm install`
- Then build the assets and run a local instance : `$ npm run build && npm run server`
- Grab a browser and reach `localhost:1337` (or update port in `Server.js` and VOILA!

I'll notify in this thread when a new production environment is available, so you don't have to clone and run an instance to workaround this issue.

**Comment by ArthurBeaulieu** [comment]
Hello @Mallabarius,
Glad to announce that we're now hosting an instance of Messe Map that uses proxy server to properly render maps from diferent origin ;

https://messemap.org/
